CREATE TABLE CHEN_FB_Post (
   PostId INT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
   RootId INT NOT NULL,
   Autore VARCHAR(16) NOT NULL,
   Testo VARCHAR(280) NOT NULL,
   [Like] INT NOT NULL,
   Commenti INT NOT NULL,
   FOREIGN KEY(RootId) REFERENCES CHEN_FB_Post(PostId)
);

DROP TABLE CHEN_FB_Post

ALTER TABLE [dbo].CHEN_FB_Post ADD  CONSTRAINT [DF_CHEN_FB_Post_Like]  DEFAULT ((0)) FOR [Like];
ALTER TABLE [dbo].CHEN_FB_Post ADD  CONSTRAINT [DF_CHEN_FB_Post_Commenti]  DEFAULT ((0)) FOR Commenti;
