CREATE TABLE CHEN_FB_Post (
   PostId INT NOT NULL IDENTITY(0,1) PRIMARY KEY, 
   RootId INT NOT NULL,
   Autore VARCHAR(16) NOT NULL,
   Testo VARCHAR(280) NOT NULL,
   [Like] INT NOT NULL,
   Commenti INT NOT NULL,
);

DROP TABLE CHEN_FB_Post
INSERT INTO CHEN_FB_Post(RootId, Autore, Testo) VALUES (0,'','')
INSERT INTO CHEN_FB_Post(RootId, Autore, Testo) VALUES (0,'Primo autore','Il testo del primo post')
SELECT * FROM CHEN_FB_Post

ALTER TABLE [dbo].CHEN_FB_Post ADD CONSTRAINT [DF_CHEN_FB_Post_Like]  DEFAULT ((0)) FOR [Like];
ALTER TABLE [dbo].CHEN_FB_Post ADD CONSTRAINT [DF_CHEN_FB_Post_Commenti]  DEFAULT ((0)) FOR Commenti;
ALTER TABLE [DBO].CHEN_FB_Post ADD CONSTRAINT [FK_CHEN_FB_Post_RootId] FOREIGN KEY(RootId) REFERENCES CHEN_FB_Post(PostId)